labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Hypervel! 🚀

        To maintain a high-quality experience for all users, please follow these guidelines when submitting your question:
  - type: checkboxes
    id: checks
    attributes:
      label: Check List
      description: Please confirm and check all the following options.
      options:
        - label: Provide a clear title and detailed description of your question.
          required: true
        - label: I have searched the existing discussions and documentation to see if my question has already been answered.
          required: true
        - label: Include any relevant code snippets or examples to help us understand your question better.
          required: true
        - label: We encourage you to help others in the community by answering questions or providing feedback on existing discussions. This helps us build a strong and supportive community around Hypervel.
          required: true
        - label: Please be respectful and considerate in your interactions with others in the community.
          required: true
        - label: Any questions labeled `not enough info` will be ignored and closed after 3 days.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Content
      description: Ask your question here. Please provide **AS MUCH DETAIL AS POSSIBLE** to help us understand your question.