blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/swooletw/hyperf-packages/discussions
    about: 'For ideas or feature requests, start a new discussion'
  - name: Support Questions & Other
    url: https://laravel-hyperf.com/docs/contributions.html#support-questions
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: Documentation issue
    url: https://github.com/swooletw/laravel-hyperf.com
    about: For documentation issues, open a pull request at the laravel-hyperf.com repository