blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/hypervel/components/discussions
    about: 'For ideas or feature requests, start a new discussion.'
  - name: Support Questions & Others
    url: https://github.com/hypervel/components/discussions
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: Documentation Issues
    url: https://github.com/hypervel/hypervel.org
    about: For documentation issues, open a pull request at the hypervel.org repository.