name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: "8.1"
            swoole: "5.0.3"
          - php: "8.2"
            swoole: "5.0.3"

    name: PHP ${{ matrix.php }} (swoole-${{ matrix.swoole }})

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: swoole-${{ matrix.swoole }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist -n -o

      - name: Execute tests
        run: |
            vendor/bin/php-cs-fixer fix --dry-run --diff
            vendor/bin/phpunit -c phpunit.xml.dist.xml
